const { chromium } = require('playwright');
const assert = require('assert');
const B = 'http://127.0.0.1:4100';
const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1067"><defs><linearGradient id="g"><stop offset="0" stop-color="#8fb8b0"/><stop offset="1" stop-color="#d9c9a8"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/></svg>';
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  await ctx.route('https://images.pexels.com/**', (r) => r.fulfill({ contentType: 'image/svg+xml', body: svg }));
  const page = await ctx.newPage(); const errors = [];
  page.on('pageerror', (e) => errors.push('PAGE ' + e.message)); page.on('console', (m) => m.type() === 'error' && !/Failed to load resource/.test(m.text()) && errors.push('CONSOLE ' + m.text()));
  const shot = (n) => page.screenshot({ path: '/tmp/kother-shots-' + n + '.png' });
  const wait = (sel, t) => page.waitForSelector(sel, { timeout: t || 8000 });
  await page.goto(B);
  await wait('.authcard'); await shot('01-auth');
  await page.click('text=Create an account'); await page.fill('#em', 'her@example.test'); await page.fill('#pw', 'a long enough password');
  await page.click('button[type=submit]');
  await wait('.topbar'); console.log('signed in; empty state:', (await page.locator('.empty h2').first().innerText()));
  assert((await page.locator('text=Test County').count()) === 0, 'no jobs before any search');
  await page.goto(B + '/#/profile'); await wait('.sections');
  await page.click('.sec-card:has(h3:text("Education")) button'); await wait('.sheet'); await page.click('text=Add education');
  await page.fill('input[name=field]', 'Finance'); await page.selectOption('select[name=level]', 'bachelor'); await shot('02-record-form');
  await page.click('text=Save Changes'); await wait('.reclist .rec');
  await page.click('.sheet >> text=Done');
  await wait('.statusbar'); console.log('status bar:', (await page.locator('.statusbar').innerText()).replace(/\n/g, ' '));
  await page.waitForSelector('.statusbar.ok', { timeout: 25000 }); console.log('status bar:', (await page.locator('.statusbar').innerText()).replace(/\n/g, ' '));
  await shot('03-status-done');
  await page.goto(B + '/#/discover'); await wait('.featured');
  console.log('sections:', await page.locator('.section h2').allInnerTexts());
  await shot('04-discover');
  await page.locator('.section .card .open').first().click(); await wait('.detail');
  console.log('detail:', await page.locator('.detail h1').innerText(), '|', (await page.locator('.inds .ind-h').allInnerTexts()).join(' / ').replace(/\n/g, ' '));
  await shot('05-detail');
  await page.click('text=Mark as applied'); await wait('text=Your application');
  await page.click('text=Edit tracking'); await wait('form[data-form=tracker]');
  await page.selectOption('select[name=status]', 'interviewing'); await page.click('text=Add interview'); await page.fill('input[name=idate]', '2026-11-03'); await page.fill('input[name=inote]', 'Panel'); await page.fill('input[name=response]', 'Phone screen done');
  await page.click('.sheet >> text=Save Changes'); await wait('text=Panel'); await shot('06-tracker');
  await page.goto(B + '/#/applications'); await wait('.rowcard'); console.log('applications row:', (await page.locator('.rowcard').first().innerText()).replace(/\n/g, ' | '));
  await page.goto(B + '/#/discover'); await wait('.featured');
  await page.locator('.section .card [data-action=save]').first().click(); await page.waitForTimeout(500);
  await page.reload(); await wait('.featured'); await page.goto(B + '/#/saved'); await wait('.rowcard'); console.log('saved after reload:', await page.locator('.rowcard h3').count());
  await page.goto(B + '/#/profile'); await wait('.sections');
  await page.click('.sec-card:has(h3:text("Salary")) button'); await page.fill('input[name=min]', '90000'); await page.click('.sheet >> text=Save Changes');
  await wait('.statusbar.run'); await page.waitForSelector('.statusbar.ok', { timeout: 25000 });
  await page.goto(B + '/#/discover'); await wait('.chips');
  const titles = [...new Set(await page.locator('.card h3, .featured h2').allInnerTexts())]; console.log('after 90k min:', titles);
  assert(!titles.includes('Instructional Aide') && !titles.includes('Accounts Payable Specialist'));
  await page.goto(B + '/#/settings'); await wait('.prov'); console.log('providers:', (await page.locator('.prov h3').allInnerTexts()).join(', ')); await shot('07-settings');
  await page.goto(B + '/#/discover'); await wait('.chips'); await page.waitForSelector('.credit-line', { timeout: 8000 }).catch(() => console.log('no credit line'));
  console.log('credit:', await page.locator('.credit-line').first().innerText().catch(() => 'none'));
  await page.click('.chip:has-text("Finance")'); await page.waitForSelector('.banner:not([hidden]) img', { timeout: 6000 }).catch(() => console.log('no banner')); await shot('08-category');
  await page.click('[data-action=notes]'); await shot('09-notes'); console.log('notes:', (await page.locator('.pop').innerText()).replace(/\n/g, ' | ').slice(0, 200)); await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(B + '/#/discover'); await wait('.featured'); await shot('10-mobile');
  console.log('overflow-x:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
  console.log('errors:', errors);
  await browser.close();
})().catch((e) => { console.error('FAIL', e.message.split('\n').slice(0, 6).join('\n')); process.exit(1); });
